version: '3.3'
services:
  postgres:
    image: postgres:16.2-bullseye
    restart: always
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: admin
      POSTGRES_DB: fireriskdb
    ports:
      - 5432:5432
    volumes:
      - ./data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - firerisk-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
    - firerisk-network

  cron:
    build: 
      context: .
      dockerfile: Dockerfile
    restart: always
    networks:
      - firerisk-network

networks:
  firerisk-network:
    driver: bridge
